-- Idempotent patches for existing Postgres databases that were initialized
-- before the current schema snapshot in postgres-init.sql.

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "role" TEXT NOT NULL DEFAULT 'USER';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dailyEmailLimit" INTEGER NOT NULL DEFAULT 100000;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "imageUploadLimitKb" INTEGER;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "senderFromEmail" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "senderReplyToEmail" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastLoginAt" TIMESTAMPTZ;

ALTER TABLE "PlatformSettings" ADD COLUMN IF NOT EXISTS "sendingDomain" TEXT;
ALTER TABLE "PlatformSettings" ADD COLUMN IF NOT EXISTS "spfVerified" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "PlatformSettings" ADD COLUMN IF NOT EXISTS "dkimVerified" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "PlatformSettings" ADD COLUMN IF NOT EXISTS "dmarcVerified" BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE "Campaign" ADD COLUMN IF NOT EXISTS "templateId" TEXT;
ALTER TABLE "Campaign" ADD COLUMN IF NOT EXISTS "provider" TEXT;
ALTER TABLE "Campaign" ADD COLUMN IF NOT EXISTS "isArchived" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "Campaign" ADD COLUMN IF NOT EXISTS "totalRecipients" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Campaign" ADD COLUMN IF NOT EXISTS "sentCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Campaign" ADD COLUMN IF NOT EXISTS "failedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Campaign" ADD COLUMN IF NOT EXISTS "skippedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Campaign" ADD COLUMN IF NOT EXISTS "startedAt" TIMESTAMPTZ;
ALTER TABLE "Campaign" ADD COLUMN IF NOT EXISTS "finishedAt" TIMESTAMPTZ;
ALTER TABLE "Campaign" ADD COLUMN IF NOT EXISTS "durationSeconds" INTEGER;

ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "provider" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "providerEventId" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "providerMessageId" TEXT;

ALTER TABLE "List" ADD COLUMN IF NOT EXISTS "isDefaultTestList" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "List" ADD COLUMN IF NOT EXISTS "isArchived" BOOLEAN NOT NULL DEFAULT FALSE;

CREATE UNIQUE INDEX IF NOT EXISTS "MailSettings_userId_key" ON "MailSettings" ("userId");
CREATE UNIQUE INDEX IF NOT EXISTS "Event_providerEventId_key" ON "Event" ("providerEventId");

CREATE TABLE IF NOT EXISTS "CampaignSendJob" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "campaignId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'QUEUED',
  "attempts" INTEGER NOT NULL DEFAULT 0,
  "provider" TEXT,
  "totalRecipients" INTEGER NOT NULL DEFAULT 0,
  "sentCount" INTEGER NOT NULL DEFAULT 0,
  "failedCount" INTEGER NOT NULL DEFAULT 0,
  "skippedCount" INTEGER NOT NULL DEFAULT 0,
  "quotaSkippedCount" INTEGER NOT NULL DEFAULT 0,
  "remainingToday" INTEGER NOT NULL DEFAULT 0,
  "requestedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "startedAt" TIMESTAMPTZ,
  "nextRunAt" TIMESTAMPTZ,
  "finishedAt" TIMESTAMPTZ,
  "lastError" TEXT,
  "skipReason" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "CampaignSendJob_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "Campaign" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "CampaignSendJob_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE "CampaignSendJob" ADD COLUMN IF NOT EXISTS "attempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CampaignSendJob" ADD COLUMN IF NOT EXISTS "provider" TEXT;
ALTER TABLE "CampaignSendJob" ADD COLUMN IF NOT EXISTS "totalRecipients" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CampaignSendJob" ADD COLUMN IF NOT EXISTS "sentCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CampaignSendJob" ADD COLUMN IF NOT EXISTS "failedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CampaignSendJob" ADD COLUMN IF NOT EXISTS "skippedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CampaignSendJob" ADD COLUMN IF NOT EXISTS "quotaSkippedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CampaignSendJob" ADD COLUMN IF NOT EXISTS "remainingToday" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CampaignSendJob" ADD COLUMN IF NOT EXISTS "requestedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE "CampaignSendJob" ADD COLUMN IF NOT EXISTS "startedAt" TIMESTAMPTZ;
ALTER TABLE "CampaignSendJob" ADD COLUMN IF NOT EXISTS "nextRunAt" TIMESTAMPTZ;
ALTER TABLE "CampaignSendJob" ADD COLUMN IF NOT EXISTS "finishedAt" TIMESTAMPTZ;
ALTER TABLE "CampaignSendJob" ADD COLUMN IF NOT EXISTS "lastError" TEXT;
ALTER TABLE "CampaignSendJob" ADD COLUMN IF NOT EXISTS "skipReason" TEXT;
ALTER TABLE "CampaignSendJob" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE "CampaignSendJob" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS "CampaignSendJob_status_requestedAt_idx" ON "CampaignSendJob" ("status", "requestedAt");
CREATE INDEX IF NOT EXISTS "CampaignSendJob_campaignId_idx" ON "CampaignSendJob" ("campaignId");

CREATE TABLE IF NOT EXISTS "SystemEvent" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "level" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "userId" TEXT,
  "campaignId" TEXT,
  "details" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "SystemEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "SystemEvent_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "Campaign" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "SystemEvent_createdAt_idx" ON "SystemEvent" ("createdAt");
CREATE INDEX IF NOT EXISTS "SystemEvent_level_createdAt_idx" ON "SystemEvent" ("level", "createdAt");
CREATE INDEX IF NOT EXISTS "SystemEvent_source_createdAt_idx" ON "SystemEvent" ("source", "createdAt");

INSERT INTO "CampaignList" ("id", "campaignId", "listId", "createdAt", "updatedAt")
SELECT
  REPLACE(c."id" || '_' || c."listId", '-', '') AS "id",
  c."id",
  c."listId",
  COALESCE(c."createdAt", NOW()),
  COALESCE(c."updatedAt", NOW())
FROM "Campaign" c
WHERE c."listId" IS NOT NULL
ON CONFLICT DO NOTHING;
