-- AlterTable
ALTER TABLE "User" ADD COLUMN "role" TEXT NOT NULL DEFAULT 'USER';
ALTER TABLE "User" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE "User" ADD COLUMN "dailyEmailLimit" INTEGER NOT NULL DEFAULT 100000;
ALTER TABLE "User" ADD COLUMN "lastLoginAt" DATETIME;

