-- AlterTable
ALTER TABLE "Campaign" ADD COLUMN "totalRecipients" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Campaign" ADD COLUMN "sentCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Campaign" ADD COLUMN "failedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Campaign" ADD COLUMN "skippedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Campaign" ADD COLUMN "startedAt" DATETIME;
ALTER TABLE "Campaign" ADD COLUMN "finishedAt" DATETIME;
ALTER TABLE "Campaign" ADD COLUMN "durationSeconds" INTEGER;
